### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ThronKatze0** [ThronKatze0/todo-app-firebase#4]
Some bug when you refresh the page, jason fix please

**Comment by mageOfstructs** [comment]
could you describe the problem a little more?

**Comment by ThronKatze0** [comment]
The id of the todos, gets assigned by using a local counter, but this counter jumps back to 0 when you refresh the page. Therefore new todos will override existing todos.

**Comment by mageOfstructs** [comment]
fixed by adding an additional field to the database
